# Generated by Django 5.0.6 on 2024-06-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=200)),
                ("penulis", models.CharField(max_length=100)),
                ("abstrak", models.TextField()),
                ("publish_date", models.DateField()),
            ],
        ),
    ]
